project: requiem
program: python
command:
  - python
  - main.py
  - --wandb
method: bayes
metric:
  name: valid_Recall@20
  goal: maximize
parameters:
  seed:
    values: [2024]
  model:
    values: ['LightGCN']
  dataset:
    values: ['Gowalla']
  min_interaction:
    values: [10]
  noise:
    values: [0.0]
  add_p:
    values: [1.0]
  out_dim:
    values: [64]
  use_gpu:
    values: [True]
  device:
    values: ['gpu']
  device_id:
    values: [0]
  batch_size:
    values: [2048]
  test_batch_size:
    values: [2048]
  patience:
    values: [20]
  val_interval:
    values: [5]
  lr:
    values: [0.001]
  weight_decay:
    values: [0.0001]
  min_epochs:
    values: [40]
  n_epochs:
    values: [1000]
  rec_top_k:
    values: [[20, 50]]
  method:
    values: ['LinearVQ']
  temp:
    values: [0]
  item_num:
    values: [0]
  num_codebook:
    values: [128, 256, 512]
  num_hirearchy:
    values: [1]
  begin_adv:
    values: [10, 15, 30, 50]
  ema:
    values: [0.3, 0.5, 0.7, 0.9, 0.99]
  alpha:
    values: [0.05, 0.1, 0.2, 0.3, 0.5]

early_terminate:
  type: hyperband
  s: 2
  eta: 3
  max_iter: 20

run_cap: 200
min_iter: 50
covergence:
  metric: valid_Recall@20
  window_size: 10
  min_improvement: 0.005
  patience: 10
