project: NeuMF-Original
program: python
command:
  - python
  - main.py
  - --wandb
method: grid
metric:
  name: valid_Recall@20
  goal: maximize
parameters:
  seed:
    values: [2024]
  model:
    values: ['NeuMF']
  dataset:
    values: ['Gowalla']
  min_interaction:
    values: [10]
  noise:
    values: [0.0]
  add_p:
    values: [1.0]
  out_dim:
    values: [64]
  use_gpu:
    values: [True]
  device:
    values: ['gpu']
  device_id:
    values: [0]
  batch_size:
    values: [256]
  test_batch_size:
    values: [256]
  patience:
    values: [100]
  val_interval:
    values: [1]
  lr:
    values: [1e-1, 1e-2, 1e-3, 1e-4, 1e-5]
  weight_decay:
    values: [1e-1, 1e-2, 1e-3, 1e-4, 1e-5]
  min_epochs:
    values: [0]
  n_epochs:
    values: [100]
  rec_top_k:
    values: [[20, 50]]
  method:
    values: ['Origin']
  temp:
    values: [0]
  item_num:
    values: [0]
  num_codebook:
    values: [-1]
  num_hirearchy:
    values: [-1]
  begin_adv:
    values: [-1]
  ema:
    values: [-1]
  beta:
    values: [-1]
  ablation:
    values: ['Origin']
  drop_rate:
    values: [-1]
  num_gradual:
    values: [-1]
